# Camera calibration data
# Generated by calibrate.py

import numpy as np

# Checkerboard used: 8x5, square size: 0.03m
# RMS reprojection error: 0.679411
# Number of calibration images: 34

# Camera intrinsic matrix (3x3)
K = np.array([[521.2250693889947, 0.0, 310.9040486676812], [0.0, 520.4850724559025, 586.2287785837725], [0.0, 0.0, 1.0]])

# Fisheye distortion coefficients (4,)
D = np.array([-0.014501409771769221, -0.011116281429951417, 0.007577250171967382, -0.002003306340373116])
